CREATE TABLE IF NOT EXISTS `audit_log_contactgroups` (
  `entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp_of_change` timestamp DEFAULT CURRENT_TIMESTAMP,
  `changed_by_username` varchar(255) NOT NULL,
  `db_operation` varchar(15) NOT NULL,
  `id` int(11) NOT NULL,
  `name_short` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `view_only` tinyint(1) NOT NULL DEFAULT '0',
  `timeframe_id` int(11) NOT NULL DEFAULT '0',
  `timezone_id` int(11) NOT NULL DEFAULT '372',
  PRIMARY KEY (`entry_id`),
  KEY `id` (`id`)
);
 
CREATE TABLE IF NOT EXISTS `audit_log_contactgroups_to_contacts` (
  `entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp_of_change` timestamp DEFAULT CURRENT_TIMESTAMP,
  `changed_by_username` varchar(255) NOT NULL,
  `db_operation` varchar(15) NOT NULL,
  `contactgroup_id` int(11) NOT NULL,
  `contact_id` int(11) NOT NULL,
  PRIMARY KEY (`entry_id`),
  KEY `contactgroup_id` (`contactgroup_id`),
  KEY `contact_id` (`contact_id`)
);
 
CREATE TABLE IF NOT EXISTS `audit_log_contacts` (
  `entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp_of_change` timestamp DEFAULT CURRENT_TIMESTAMP,
  `changed_by_username` varchar(255) NOT NULL,
  `db_operation` varchar(15) NOT NULL,
  `id` int(11) NOT NULL,
  `admin` tinyint(1) NOT NULL,
  `username` varchar(255) NOT NULL,
  `full_name` varchar(255) NOT NULL,
  `email` varchar(255) NULL,
  `phone` varchar(255) NULL,
  `mobile` varchar(255) NULL,
  `section` varchar(255) NULL,
  `growladdress` varchar(255) NULL,
  `password` varchar(255) NULL,
  `timeframe_id` int(11) NOT NULL DEFAULT '0',
  `timezone_id` int(11) NOT NULL DEFAULT '372',
  `restrict_alerts` tinyint(1) NULL,
  PRIMARY KEY (`entry_id`),
  KEY `id` (`id`)
);
 
CREATE TABLE IF NOT EXISTS `audit_log_escalations_contacts` (
  `entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp_of_change` timestamp DEFAULT CURRENT_TIMESTAMP,
  `changed_by_username` varchar(255) NOT NULL,
  `db_operation` varchar(15) NOT NULL,
  `id` int(11) NOT NULL,
  `notification_id` int(11) NOT NULL,
  `on_ok` tinyint(1) DEFAULT '0',
  `on_warning` tinyint(1) DEFAULT '0',
  `on_critical` tinyint(1) DEFAULT '0',
  `on_unknown` tinyint(1) DEFAULT '0',
  `on_host_up` tinyint(1) DEFAULT '0',
  `on_host_unreachable` tinyint(1) DEFAULT '0',
  `on_host_down` tinyint(1) DEFAULT '0',
  `on_type_problem` tinyint(1) DEFAULT '0',
  `on_type_recovery` tinyint(1) DEFAULT '0',
  `on_type_flappingstart` tinyint(1) DEFAULT '0',
  `on_type_flappingstop` tinyint(1) DEFAULT '0',
  `on_type_flappingdisabled` tinyint(1) DEFAULT '0',
  `on_type_downtimestart` tinyint(1) DEFAULT '0',
  `on_type_downtimeend` tinyint(1) DEFAULT '0',
  `on_type_downtimecancelled` tinyint(1) DEFAULT '0',
  `on_type_acknowledgement` tinyint(1) DEFAULT '0',
  `on_type_custom` tinyint(1) DEFAULT '0',
  `notify_after_tries` varchar(255) NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry_id`),
  KEY `id` (`id`),
  KEY `notification_id` (`notification_id`)
);
 
 
CREATE TABLE IF NOT EXISTS `audit_log_escalations_contacts_to_contactgroups` (
  `entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp_of_change` timestamp DEFAULT CURRENT_TIMESTAMP,
  `changed_by_username` varchar(255) NOT NULL,
  `db_operation` varchar(15) NOT NULL,
  `escalation_contacts_id` int(11) NOT NULL,
  `contactgroup_id` int(11) NOT NULL,
  PRIMARY KEY (`entry_id`),
  KEY `contactgroup_id` (`contactgroup_id`),
  KEY `escalation_contacts_id` (`escalation_contacts_id`)
);
 
CREATE TABLE IF NOT EXISTS `audit_log_escalations_contacts_to_methods` (
  `entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp_of_change` timestamp DEFAULT CURRENT_TIMESTAMP,
  `changed_by_username` varchar(255) NOT NULL,
  `db_operation` varchar(15) NOT NULL,
  `escalation_contacts_id` int(11) NOT NULL,
  `method_id` int(11) NOT NULL,
  PRIMARY KEY (`entry_id`),
  KEY `escalation_contacts_id` (`escalation_contacts_id`),
  KEY `method_id` (`method_id`)
);
 
CREATE TABLE IF NOT EXISTS `audit_log_holidays` (
  `entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp_of_change` timestamp DEFAULT CURRENT_TIMESTAMP,
  `changed_by_username` varchar(255) NOT NULL,
  `db_operation` varchar(15) NOT NULL,
  `id` int(11) NOT NULL,
  `holiday_name` varchar(255) NULL,
  `timeframe_id` int(11) NULL,
  `contact_id` int(11) NULL,
  `holiday_start` datetime NOT NULL,
  `holiday_end` datetime NOT NULL,
  PRIMARY KEY (`entry_id`),
  KEY `id` (`id`),
  KEY `contact_id` (`contact_id`),
  KEY `timeframe_id` (`timeframe_id`)
);
 
CREATE TABLE IF NOT EXISTS `audit_log_notifications` (
  `entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp_of_change` timestamp DEFAULT CURRENT_TIMESTAMP,
  `changed_by_username` varchar(255) NOT NULL,
  `db_operation` varchar(15) NOT NULL,
  `id` int(11) NOT NULL,
  `notification_name` varchar(255) NULL,
  `notification_description` varchar(1024) NULL,
  `active` tinyint(1) NOT NULL,
  `username` varchar(255) NOT NULL,
  `recipients_include` varchar(255) NULL,
  `recipients_exclude` varchar(255) NULL,
  `hosts_include` varchar(255) NULL,
  `hosts_exclude` varchar(255) NULL,
  `hostgroups_include` varchar(255) NULL,
  `hostgroups_exclude` varchar(255) NULL,
  `services_include` varchar(255) NULL,
  `services_exclude` varchar(255) NULL,
  `servicegroups_include` varchar(255) NULL,
  `servicegroups_exclude` varchar(255) NULL,
  `customvariables_include` varchar(1023) NOT NULL,
  `customvariables_exclude` varchar(1023) NOT NULL,
  `notify_after_tries` varchar(10) NOT NULL DEFAULT '0',
  `let_notifier_handle` tinyint(1) DEFAULT '0',
  `rollover` tinyint(1) DEFAULT '0',
  `reloop_delay` int(11) DEFAULT '0',
  `on_ok` tinyint(1) DEFAULT '0',
  `on_warning` tinyint(1) DEFAULT '0',
  `on_unknown` tinyint(1) DEFAULT '0',
  `on_host_unreachable` tinyint(1) DEFAULT '0',
  `on_critical` tinyint(1) DEFAULT '0',
  `on_host_up` tinyint(1) DEFAULT '0',
  `on_host_down` tinyint(1) DEFAULT '0',
  `on_type_problem` tinyint(1) DEFAULT '0',
  `on_type_recovery` tinyint(1) DEFAULT '0',
  `on_type_flappingstart` tinyint(1) DEFAULT '0',
  `on_type_flappingstop` tinyint(1) DEFAULT '0',
  `on_type_flappingdisabled` tinyint(1) DEFAULT '0',
  `on_type_downtimestart` tinyint(1) DEFAULT '0',
  `on_type_downtimeend` tinyint(1) DEFAULT '0',
  `on_type_downtimecancelled` tinyint(1) DEFAULT '0',
  `on_type_acknowledgement` tinyint(1) DEFAULT '0',
  `on_type_custom` tinyint(1) DEFAULT '0',
  `timezone_id` int(11) NOT NULL DEFAULT '372',
  `timeframe_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry_id`),
  KEY `id` (`id`),
  KEY `time` (`id`,`timeframe_id`)
);
 
CREATE TABLE IF NOT EXISTS `audit_log_notifications_to_contactgroups` (
  `entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp_of_change` timestamp DEFAULT CURRENT_TIMESTAMP,
  `changed_by_username` varchar(255) NOT NULL,
  `db_operation` varchar(15) NOT NULL,
  `notification_id` int(11) NOT NULL,
  `contactgroup_id` int(11) NOT NULL,
  PRIMARY KEY (`entry_id`),
  KEY `notification_id` (`notification_id`),
  KEY `contactgroup_id` (`contactgroup_id`)
);
 
CREATE TABLE IF NOT EXISTS `audit_log_notifications_to_contacts` (
  `entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp_of_change` timestamp DEFAULT CURRENT_TIMESTAMP,
  `changed_by_username` varchar(255) NOT NULL,
  `db_operation` varchar(15) NOT NULL,
  `notification_id` int(11) NOT NULL,
  `contact_id` int(11) NOT NULL,
  PRIMARY KEY (`entry_id`),
  KEY `notification_id` (`notification_id`),
  KEY `contact_id` (`contact_id`)
);
 
CREATE TABLE IF NOT EXISTS `audit_log_notifications_to_methods` (
  `entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp_of_change` timestamp DEFAULT CURRENT_TIMESTAMP,
  `changed_by_username` varchar(255) NOT NULL,
  `db_operation` varchar(15) NOT NULL,
  `notification_id` int(11) NOT NULL,
  `method_id` int(11) NOT NULL,
  PRIMARY KEY (`entry_id`),
  KEY `notification_id` (`notification_id`),
  KEY `method_id` (`method_id`)
);
 
CREATE TABLE IF NOT EXISTS `audit_log_timeframes` (
  `entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp_of_change` timestamp DEFAULT CURRENT_TIMESTAMP,
  `changed_by_username` varchar(255) NOT NULL,
  `db_operation` varchar(15) NOT NULL,
  `id` int(11) NOT NULL,
  `timeframe_name` varchar(60) NOT NULL,
  `dt_validFrom` datetime NOT NULL,
  `dt_validTo` datetime NOT NULL,
  `day_monday_all` tinyint(1) DEFAULT '0',
  `day_monday_1st` tinyint(1) DEFAULT '0',
  `day_monday_2nd` tinyint(1) DEFAULT '0',
  `day_monday_3rd` tinyint(1) DEFAULT '0',
  `day_monday_4th` tinyint(1) DEFAULT '0',
  `day_monday_5th` tinyint(1) DEFAULT '0',
  `day_monday_last` tinyint(1) DEFAULT '0',
  `day_tuesday_all` tinyint(1) DEFAULT '0',
  `day_tuesday_1st` tinyint(1) DEFAULT '0',
  `day_tuesday_2nd` tinyint(1) DEFAULT '0',
  `day_tuesday_3rd` tinyint(1) DEFAULT '0',
  `day_tuesday_4th` tinyint(1) DEFAULT '0',
  `day_tuesday_5th` tinyint(1) DEFAULT '0',
  `day_tuesday_last` tinyint(1) DEFAULT '0',
  `day_wednesday_all` tinyint(1) DEFAULT '0',
  `day_wednesday_1st` tinyint(1) DEFAULT '0',
  `day_wednesday_2nd` tinyint(1) DEFAULT '0',
  `day_wednesday_3rd` tinyint(1) DEFAULT '0',
  `day_wednesday_4th` tinyint(1) DEFAULT '0',
  `day_wednesday_5th` tinyint(1) DEFAULT '0',
  `day_wednesday_last` tinyint(1) DEFAULT '0',
  `day_thursday_all` tinyint(1) DEFAULT '0',
  `day_thursday_1st` tinyint(1) DEFAULT '0',
  `day_thursday_2nd` tinyint(1) DEFAULT '0',
  `day_thursday_3rd` tinyint(1) DEFAULT '0',
  `day_thursday_4th` tinyint(1) DEFAULT '0',
  `day_thursday_5th` tinyint(1) DEFAULT '0',
  `day_thursday_last` tinyint(1) DEFAULT '0',
  `day_friday_all` tinyint(1) DEFAULT '0',
  `day_friday_1st` tinyint(1) DEFAULT '0',
  `day_friday_2nd` tinyint(1) DEFAULT '0',
  `day_friday_3rd` tinyint(1) DEFAULT '0',
  `day_friday_4th` tinyint(1) DEFAULT '0',
  `day_friday_5th` tinyint(1) DEFAULT '0',
  `day_friday_last` tinyint(1) DEFAULT '0',
  `day_saturday_all` tinyint(1) DEFAULT '0',
  `day_saturday_1st` tinyint(1) DEFAULT '0',
  `day_saturday_2nd` tinyint(1) DEFAULT '0',
  `day_saturday_3rd` tinyint(1) DEFAULT '0',
  `day_saturday_4th` tinyint(1) DEFAULT '0',
  `day_saturday_5th` tinyint(1) DEFAULT '0',
  `day_saturday_last` tinyint(1) DEFAULT '0',
  `day_sunday_all` tinyint(1) DEFAULT '0',
  `day_sunday_1st` tinyint(1) DEFAULT '0',
  `day_sunday_2nd` tinyint(1) DEFAULT '0',
  `day_sunday_3rd` tinyint(1) DEFAULT '0',
  `day_sunday_4th` tinyint(1) DEFAULT '0',
  `day_sunday_5th` tinyint(1) DEFAULT '0',
  `day_sunday_last` tinyint(1) DEFAULT '0',
  `time_monday_start` time DEFAULT '00:00:00',
  `time_monday_stop` time DEFAULT '00:00:00',
  `time_monday_invert` tinyint(1) DEFAULT '0',
  `time_tuesday_start` time DEFAULT '00:00:00',
  `time_tuesday_stop` time DEFAULT '00:00:00',
  `time_tuesday_invert` tinyint(1) DEFAULT '0',
  `time_wednesday_start` time DEFAULT '00:00:00',
  `time_wednesday_stop` time DEFAULT '00:00:00',
  `time_wednesday_invert` tinyint(1) DEFAULT '0',
  `time_thursday_start` time DEFAULT '00:00:00',
  `time_thursday_stop` time DEFAULT '00:00:00',
  `time_thursday_invert` tinyint(1) DEFAULT '0',
  `time_friday_start` time DEFAULT '00:00:00',
  `time_friday_stop` time DEFAULT '00:00:00',
  `time_friday_invert` tinyint(1) DEFAULT '0',
  `time_saturday_start` time DEFAULT '00:00:00',
 `time_saturday_stop` time DEFAULT '00:00:00',
  `time_saturday_invert` tinyint(1) DEFAULT '0',
  `time_sunday_start` time DEFAULT '00:00:00',
  `time_sunday_stop` time DEFAULT '00:00:00',
  `time_sunday_invert` tinyint(1) DEFAULT '0',
  PRIMARY KEY `entry_id` (`entry_id`),
  KEY `id` (`id`)
);
 
ALTER TABLE escalation_stati ADD COLUMN customvariables varchar(1023) NULL;
ALTER TABLE escalation_stati ADD COLUMN impact varchar(4095) NULL;
ALTER TABLE notifications ADD COLUMN customvariables_include varchar(2047) NULL;
ALTER TABLE notifications ADD COLUMN customvariables_exclude varchar(2047) NULL;
ALTER TABLE tmp_commands ADD COLUMN customvariables varchar(1023) NULL;
ALTER TABLE tmp_commands ADD COLUMN impact varchar(4095) NULL;
 
UPDATE information SET content =  '2200' WHERE type =  'dbversion' and content = '2000'
